version: "3.7"
services:
  #MySQL Service
#  db:
#    image: mysql:5.7.22
#    container_name: db
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: getLocalProject
#      MYSQL_ROOT_PASSWORD: mysql_root_password
#    command:
#      - mysqld
#      - --default_storage_engine=InnoDB
#      - --character-set-server=utf8
#      - --collation-server=utf8_general_ci
#      - --init-connect=SET NAMES utf8
#      - --innodb_log_file_size=256M
#      - --innodb_buffer_pool_size=3GB
#      - --max_allowed_packet=20M
#      - --bulk_insert_buffer_size=20M
#      - --query_cache_size=32M
#      - --skip-character-set-client-handshake
#      - --skip-host-cache
#      - --wait_timeout=600
#    networks:
#      - app-network

  #PHP Laravel Service
  php:
    working_dir: /var/www/html/getLocalProject
    build: .
    restart: always
    tty: true
    ports:
      - "8000:8000"
      - "5001:5001"
    volumes:
      - ./getLocalProject/app:/var/www/html/getLocalProject/app
      - ./getLocalProject/bootstrap:/var/www/html/getLocalProject/bootstrap
      - ./getLocalProject/config:/var/www/html/getLocalProject/config
      - ./getLocalProject/database:/var/www/html/getLocalProject/database
      - ./getLocalProject/public:/var/www/html/getLocalProject/public
      - ./getLocalProject/resources:/var/www/html/getLocalProject/resources
      - ./getLocalProject/routes:/var/www/html/getLocalProject/routes
      - ./getLocalProject/storage:/var/www/html/getLocalProject/storage
#      - ./getLocalProject/vendor:/var/www/html/getLocalProject/vendor
      - ./getLocalProject/tests:/var/www/html/getLocalProject/tests
      - ./getLocalProject/.editorconfig:/var/www/html/getLocalProject/.editorconfig
      - ./getLocalProject/.env:/var/www/html/getLocalProject/.env
      - ./getLocalProject/.env.example:/var/www/html/getLocalProject/.env.example
      - ./getLocalProject/.styleci.yml:/var/www/html/getLocalProject/.styleci.yml
      - ./getLocalProject/artisan:/var/www/html/getLocalProject/artisan
      - ./getLocalProject/composer.json:/var/www/html/getLocalProject/composer.json
      - ./getLocalProject/composer.lock:/var/www/html/getLocalProject/composer.lock
      - ./getLocalProject/package.json:/var/www/html/getLocalProject/package.json
      - ./getLocalProject/phpunit.xml:/var/www/html/getLocalProject/phpunit.xml
      - ./getLocalProject/server.php:/var/www/html/getLocalProject/server.php
      - ./getLocalProject/webpack.mix.js:/var/www/html/getLocalProject/webpack.mix.js
#    depends_on:
#      - db
#    links:
#      - db
    command: bash -c "composer install && php artisan serve --host 0.0.0.0 --port 5001"
#    command: bash -c "composer install && php artisan migrate && php artisan serve --host 0.0.0.0 --port 5001"
#    command: bash -c "composer install && php artisan make:migration 2014_10_12_000000_create_users_table && php artisan make:migration 2014_10_12_100000_create_password_resets_table && php artisan make:migration 2019_08_19_000000_create_failed_jobs_table && php artisan make:migration 2020_10_31_221320_create_localizacaos_table && php artisan serve --host 0.0.0.0 --port 5001"
#    networks:
#      - app-network

#Docker Networks
#networks:
#  app-network:
#    driver: bridge