version: "3.7" 
services:
  php:
    build:
      context: .
    image: php:7.4-fpm
    container_name: php
    ports:
      - "9000:9000"
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t getLocalProject/